key-encryption-check (#4755)
* key-encryption-check

* key-encryption-check

* key-encryption-check with test.ejson without encryption

* delete file

* key-encryption-check with test.ejson without encryption

* key-encryption-check

diff --git a/script/Jenkinsfile b/script/Jenkinsfile
--- a/script/Jenkinsfile
+++ b/script/Jenkinsfile
@@ -24,6 +24,48 @@ def send_email() {
         replyTo: "${mailRecipients}"
 }
 
+//Encryption check
+def keycheck() {
+
+   image = "792634465463.dkr.ecr.us-east-1.amazonaws.com/freshdesk/backend"
+
+   docker.image(image).inside {
+
+      source = params.ghprbSourceBranch
+
+      sh  """#!/bin/bash
+	       source /etc/profile.d/rvm.sh
+	       cd /home/jenkins/
+	       git clone -b $source git@github.com:freshdesk/helpkit.git
+	       cd /home/jenkins/helpkit/
+	      """
+      
+      sh '''#!/bin/bash
+         cd /home/jenkins/helpkit
+         source /etc/profile.d/rvm.sh
+         function validate_ejson() {
+                  git diff --raw $ghprbSourceBranch origin/$ghprbTargetBranch
+                  for f in \$(git diff --raw $ghprbSourceBranch origin/$ghprbTargetBranch | awk  '{print \$6}' | grep .ejson)
+                     do
+                        tf=\$(mktemp)
+                        git show :\$f > \$tf
+                        ./deploy/config/dynamic_config_util.rb validate --file="\$tf"
+                        if [ \$? -ne 0 ]; then
+                           echo "ERROR: EJSON file \$f validation failed" && { echo "ERROR: You have secrets not encrypted, run \"ejson encrypt ./deploy/config/*.ejson\" and try again"; exit 1; }
+                        fi
+                        rm -f \$tf
+                     done
+         }
+
+         validate_ejson'''
+
+   }
+ 
+         
+         
+
+}
+
 //Specfiy the branch to checkout based on PR condition
 def checkout(type) {
      
@@ -178,8 +220,9 @@ def distributed_run(category) {
 							   }else{
 							        checkout("normal")
 							   }
-							
-				             //Build setup
+
+
+                           //Build setup
 							    if(category != 'pronto') {
 					    			//Intialization process
 					            	build_setup(category)
@@ -195,6 +238,7 @@ def distributed_run(category) {
 						            if(category != 'pronto') {
 						               echo "issue with test execution" + e
                            failing_category = category
+                                 echo "Build UNSTABLE"
 						               currentBuild.result = 'UNSTABLE'
 						            }else{
 						                echo "Verifiy Pronto code" + e
@@ -209,6 +253,10 @@ def distributed_run(category) {
 								            publish_report(category)
 						    		}
 						         }
+
+                        
+							
+				             
 					    }	         
                   }
             }
@@ -224,6 +272,8 @@ def distributed_run(category) {
      sh "mkdir -p /home/jenkins/workspace/$jobName/tmp/"
      sh "mkdir -p /home/jenkins/workspace/$jobName/test/reports/"
       
+    //Encryption check starts here
+    keycheck();
      
     //Parallel Test starts here
     parallel Public: {
